-- CREAR FUNCION SQL PARA REINICIAR SECUENCIA
CREATE OR REPLACE FUNCTION reset_sequence(sequence_name text) RETURNS void AS $$
BEGIN
  EXECUTE format('ALTER SEQUENCE %I RESTART WITH 1;', sequence_name);
END;
$$ LANGUAGE plpgsql;


-- EJEMPLO PARA EJECUTAR FUNCION DE REINCIO DE SECUENCIA
SELECT reset_sequence('NAME_SECUENCE');


-- CREATE SECUENCIAS
  -- SECUENCIA ANUAL PARA CORRELATIVO DE ESTAMPILLAS
CREATE SEQUENCE annual_correlative_tax_stamps
INCREMENT BY 1
START WITH 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

-- SECUENCIA DIARIA PARA CORRELATIVO DE PETICIONES AL BANCO
CREATE SEQUENCE daily_correlative_request_bank
INCREMENT BY 1
START WITH 1
NO MINVALUE
NO MAXVALUE
CACHE 1;
